### ISSUE TITLE
What to do since processing 2 and 3 are incompatible 

### ISSUE THREAD

**Issue by hanss314** [carykh/neuralNetworkLanguageDetection#11]
After doing some work, I found that processing 2 and 3 don't go together so well. Specifically, customized window size only works for processing 2. Should we make everything work only for 2 and abandon processing 3 or should we add a few commented out lines of code meant for processing 3. Or do we want to open a new branch for processing 3 compatability. There areally a lot of things that we can do to fix compatibility issues. What does everyone want? Voting ends Dec. 8.

**Comment by Chronophylos** [comment]
I don't mind using Processing 2 instead of Processing 3. Sadly there is no Processing 2 Package for Arch Linux. But I could build it from source, so no problem there.
If reverting to version 2 fixes these problems I'm for Processing 2.

**Comment by adamthedog** [comment]
I think we should all just use 2. Sorta like Python 3.5, some new things are annoying, such as no custom windows size. Really the only good thing it has to offer is a new layout not based on the arduino source.

**Comment by hanss314** [comment]
So do you want to abandon 3 or still  add some compatibility for 3 like commented out code or another branch or repo?

**Comment by hanss314** [comment]
Also, there is a processing 2 version for linux that works on ubuntu. I don't know Linux very well but will that version work on linux?

**Comment by ZweiSpeedruns** [comment]
another branch for processing 3 would be best. Including a separate, commented-out version of the source in the file is pretty nasty.

**Comment by Chronophylos** [comment]
About Linux. Processing 2 and 3 both use a loose filesystem i.e. no dependencies (execpt Java), everything is in the folder of Processing. This means it should run out of the box. And it does for me (2 and 3).
Also: Should we consider a 'community' Repository?

**Comment by ZweiSpeedruns** [comment]
With FOSS anyone can contribute to the main repo. Separate repos are typically created when a person from the community and the creator of the main repo disagree on the direction the software should go, resulting in a separate fork.

**Comment by hanss314** [comment]
Seems like most people would be fine with two branches. In that case I'll close the issue.
