### ISSUE TITLE
size() cannot be used here line 42

### ISSUE THREAD

**Issue by zekeroonie** [carykh/neuralNetworkLanguageDetection#8]

**Comment by hanss314** [comment]
What version of processing are you using?
 size() is deprecated in processing 3.

**Comment by Chronophylos** [comment]
fixed in #9 
I moved size() in settings()

**Comment by ZweiSpeedruns** [comment]
this is intended to be run in processing 2

**Comment by hanss314** [comment]
Also size () shouldn't be in settings(). It should be the first method in setup ( ).

**Comment by TyroneStoreOfHummus** [comment]
Oops, i did a branch thing where i moved size to settings

**Comment by Chronophylos** [comment]
But why Processing2?

**Comment by hanss314** [comment]
Did some research. settings() is only in processing 3. So if you size() there in processing 2 it won't work properly. Settings() rind before setup().

**Comment by hanss314** [comment]
Cary made it in processing 2.

**Comment by TyroneStoreOfHummus** [comment]
He says that it should work in all versions

**Comment by Chronophylos** [comment]
But why 2? If they even recommend 3

**Comment by zekeroonie** [comment]
I was able to fix it by deleting that line, and putting in a new line under void setup() with size(1100,600) 
I did testing and figured out that 1100,600 is the best possible

**Comment by zekeroonie** [comment]
not POSSIBLE, but best ish

**Comment by TyroneStoreOfHummus** [comment]
no but you dont know how many languages there will be, and htat's what
affects it most

**Comment by TyroneStoreOfHummus** [comment]
No but you cant just use hard codedness, because it depens on num of
languages
